puts "The Students of Villains Academy"
puts "_____________"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corelone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "The Terminator"
puts "Freddie Krueger"
puts "The Joker"
puts "Joffery Baratheon"
puts "Norman Bates"
